### PR TITLE
Fix spatial subseting with GDAL warp.

### PR DESCRIPTION
**Pull request by radosuav**

### CODE REVIEW

**Comment by j08lue** [comment]
Is this another cherry pick from QGIS Processing 2.18?

**Comment by radosuav** [comment]
No, it's a bug in 2.18. I'll make a PR for it soon.

**Comment by j08lue** [comment]
Thanks for giving us the fixes first. 👍

**Comment by j08lue** [comment]
This is now updated in both 64 bit and 32 bit installation packages on the DataStore.

**Pull request merged**
